Write an initial introduction
llsoftsec/llsoftsecbook pull request #15
Opened 2021-09-22 13:15 UTC by kbeyls

The introduction explains:
1. The purpose of the book.
2. The intended audience.
3. Why we started creating this book:
   - We don't know of any other similar ones.
   - There is a need for a book like this.
4. Explain why we chose to develop this book as an open source project.
5. Give some basic pointers on how readers can contribute to the book.

2021-09-22 13:24 UTC, fpetrogalli commented on book.md
> +How this book is created
FWIW, I prefer ATX-style headings as they make the sectioning level explicit in the source. See https://pandoc.org/MANUAL.html#headings

2021-09-22 13:44 UTC, kbeyls commented on book.md
> +How this book is created
Thanks @fpetrogalli!
I have that change lined up in one of my future pull requests ;)

2021-09-24 12:23 UTC, kbeyls commented on book.md
> +How this book is created
I've just made that change as part of this PR. Thanks!

2021-09-27 12:54 UTC, g-kouv commented on book.md
> +overview on this topic. Kristof Beyls and Georgia Kouvelli, both compiler
extra l

2021-09-27 12:56 UTC, g-kouv requested changes
Just the one typo!

2021-09-27 13:19 UTC, kbeyls commented on book.md
> +overview on this topic. Kristof Beyls and Georgia Kouvelli, both compiler
This should now be fixed. Apologies for the typo!

2021-09-27 13:30 UTC, merged