Add chapter on underhanded code (#232)
llsoftsec/llsoftsecbook pull request #239
Opened 2024-05-02 18:37 UTC by wanders

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239)

2024-05-03 13:01 UTC, kbeyls requested changes
Thank you very much for this contribution @wanders !
The comments I've left are just very minor nit picks.
The text reads easily and explains the issues well.

The only other thing I'd like to add to this change is to add copyright info for your contribution. (We try to keep the copyright information up-to-date)
See the top of the `book.md` source file, which looks like this at the moment:
```
---
SPDX-License-Identifier: CC-BY-4.0
copyright:
  - SPDX-FileCopyrightText: Copyright 2021-2024 Arm Limited <open-source-office@arm.com>
  - SPDX-FileCopyrightText: Copyright 2023 Bill Wendling <morbo@google.com>
  - SPDX-FileCopyrightText: Copyright 2023 Lucian Popescu <lucian.popescu187@gmail.com>
```
Could you add another `SPDX-FileCopyrightText` line with the appropriate information?

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-:-NwyWsOp-jAtGcm-8xq9:bwatng2)* status: 0 of 2 files reviewed, 14 unresolved discussions (waiting on @wanders)

___
*[`book.md` line 2495 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyScqa3XTyq2Q-VQG2:-NwyScqbEk-XOKfMACOg:b3woyr1) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2495)):*
> ```Markdown
> on code inspection. However the same applies also when the
> underhanded behavior has been added by mistake - in fact the ideal
> attack would also give the attacker the possibility to say it was a
> ```

s/a honest/an honest/
___
*[`book.md` line 2499 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwySnsr8D0SmCLIf7XF:-NwySnsr8D0SmCLIf7XG:bv9z2f6) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2499)):*
> ```Markdown
> 
> [@Wheeler2020] provides a more systematic view of underhanded code
> than is given here. This chapter present some examples to give an
> ```

s/present/presents/
___
*[`book.md` line 2507 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyT0mn11w4MNZunf1g:-NwyT0mn11w4MNZunf1h:b-h63fuj) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2507)):*
> ```Markdown
> 
> Probably the most classic example of underhanded code in C-style
> languages is code that takes advantage of the fact that assignment
> ```

maybe "the assignment (`=`) and the equality (`==`) operator look very similar"?
___
*[`book.md` line 2537 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyTlqe1CRViNv82IN-:-NwyTlqe1CRViNv82IN0:b-71cpv5) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2537)):*
> ```Markdown
> added to the language [@pep572] (in python 3.8) the more visually
> distinct "walrus operator" `:=` was used to avoid this risk of
> confusing with comparison operator. Even in cases where it is an
> ```

s/with comparison operator/with the comparison operator/?
___
*[`book.md` line 2539 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyTuLWCYyKvdqrWugs:-NwyTuLWCYyKvdqrWugt:b-nygyky) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2539)):*
> ```Markdown
> confusing with comparison operator. Even in cases where it is an
> existing language the compiler can provide options to forbid risky
> constructs for those how want and can opt in to it, essentially
> ```

s/how/who/?
___
*[`book.md` line 2544 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyTxwp7PB07XZiL_nu:-NwyTxwp7PB07XZiL_nv:b-jkxoox) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2544)):*
> ```Markdown
> ## goto fail
> 
> The "goto-fail" bug, officially known as CVE-2014-1266, caused Apple
> ```

I think it may be useful to add a link to CVE-2014-1266, e.g. to https://nvd.nist.gov/vuln/detail/CVE-2014-1266.
What do you think?
___
*[`book.md` line 2577 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyURfv2JUYAfrykt30:-NwyURfv2JUYAfrykt31:b-1zvrqb) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2577)):*
> ```Markdown
> ```
> 
> At the time of they bug they didn't but nowadays both gcc and clang
> ```

replace the first "they" with "the".
___
*[`book.md` line 2578 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyUXv07lYYP6w2DPd7:-NwyUXv07lYYP6w2DPd8:b-6ppqd4) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2578)):*
> ```Markdown
> 
> At the time of they bug they didn't but nowadays both gcc and clang
> have a `-Wmisleading-indentation` option that detects kind this
> ```

s/kind this/this kind of/
___
*[`book.md` line 2581 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyUdTg1ejw415XzRDs:-NwyUdTg1ejw415XzRDt:by0k7pd) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2581)):*
> ```Markdown
> problem.
> 
> Also automatic formatting such as clang-format would help finding this
> ```

maybe s/formatting/formatting tools/?
___
*[`book.md` line 2588 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyUoMV0ZU84SEKmktA:-NwyUoMV0ZU84SEKmktB:b-c5thtd) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2588)):*
> ```Markdown
> "Trojan Source" attacks described by [@Boucher2023] is another way
> underhanded code could be achieved by doing something that makes the
> editor (or other thing that displays code to user) render the code in
> ```

s/to user/to the user/?
___
*[`book.md` line 2592 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyUyGL8V2RTBOAZXxW:-NwyUyGL8V2RTBOAZXxX:b9mknv6) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2592)):*
> ```Markdown
> 
> This is done by using unicode features. Support for bidirectional text
> is one such feature, where it has special chars to mark regions of
> ```

I'm wondering if "characters" instead of "chars" would be more correct here?
___
*[`book.md` line 2597 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyVH957qRXGoMgr9K4:-NwyVH957qRXGoMgr9K5:brwdgtt) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2597)):*
> ```Markdown
> they can make the text render in a way that makes a word look like it
> is inside a comment but to the compiler which parses it in the order
> it appears in the file it is after the comment.
> ```

maybe s/it appears in the file it is after the comment/it appears in the file in, sees it as after the comment/?
___
*[`book.md` line 2599 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyWBbt7-8dZKVRb7RY:-NwyWBbt7-8dZKVRb7RZ:b-443m9k) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2599)):*
> ```Markdown
> it appears in the file it is after the comment.
> 
> `gcc` provides `-Wbidi-chars` to detect usage of writing direction
> ```

Maybe it would be useful to also mention that the on the clang side, the decision was to not integrate the check in clang, but rather in clang-tidy, see https://bugs.chromium.org/p/llvm/issues/detail?id=11.
___
*[`book.md` line 2604 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyWgTQ3m7VowhmwUXm:-NwyWgTQ3m7VowhmwUXn:bxlxqt6) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2604)):*
> ```Markdown
> Another variant of "trojan source" is usage of homoglyphs, different
> characters that looks similar or even identical (depending on
> font). As an example unicode contains the character "Division Slash"
> ```

Maybe s/As an example/As an example,/?


<!-- Sent from Reviewable [...]

2024-05-03 13:42 UTC, wanders commented
Thanks, I'll try to carve out some time during the weekend to update this. Have not used reviewable.io before - I guess pushing amended commit with fixes to my branch is expected workflow?





<!-- Sent from Reviewable.io -->

2024-05-03 13:47 UTC, kbeyls commented
> Thanks, I'll try to carve out some time during the weekend to update this. Have not used reviewable.io before - I guess pushing amended commit with fixes to my branch is expected workflow?

That's great :)

If you prefer, you don't have to use reviewable.io; but we've found it is better at keeping track of and not loosing review comments, especially when there are further commits, or amended commits to the pull request.

Yes, pushing commits to your branch should update this pull request automatically.
There is no need to amend/change the commit you already have on your branch, we can do a "squash and merge" merge that will squash all extra commits done into a single commit when merging into mainline. But if you prefer to alter/amend your current commit and force push to your branch, that is fine too.

2024-05-05 20:16 UTC, wanders reviewed
Updated according to comments (hopefully). Also fixed capitalization of GCC and Clang.

("squash and merge" is my least favorite way to merge things (as what has been reviewed is not exactly same thing as what gets merged). And also I wanted to try out reviewable.io's handling of history rewriting -- and it seems to be nice)

> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-:-Nx9NV_k7xcvZAZzPWdw:bg0vocj)* status: 0 of 2 files reviewed, 14 unresolved discussions (waiting on @kbeyls)

___
*[`book.md` line 2495 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyScqa3XTyq2Q-VQG2:-Nx9MxPFBL3zMjM1X-3N:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2495)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

s/a honest/an honest/
</blockquote></details>

Done.
___
*[`book.md` line 2499 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwySnsr8D0SmCLIf7XF:-Nx9MzNG8W2Jt_8nIAvi:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2499)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

s/present/presents/
</blockquote></details>

Done.
___
*[`book.md` line 2507 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyT0mn11w4MNZunf1g:-Nx9N0_4DezLfLUdLxPX:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2507)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

maybe "the assignment (`=`) and the equality (`==`) operator look very similar"?
</blockquote></details>

Done.
___
*[`book.md` line 2537 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyTlqe1CRViNv82IN-:-Nx9N3HB-2_3bhbDySLf:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2537)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

s/with comparison operator/with the comparison operator/?
</blockquote></details>

Done.
___
*[`book.md` line 2539 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyTuLWCYyKvdqrWugs:-Nx9N5-Z8UGFRmnNTbrW:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2539)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

s/how/who/?
</blockquote></details>

Done.
___
*[`book.md` line 2544 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyTxwp7PB07XZiL_nu:-Nx9NBPpA1XM1Bm-dO2l:b7e4hsb) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2544)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

I think it may be useful to add a link to CVE-2014-1266, e.g. to https://nvd.nist.gov/vuln/detail/CVE-2014-1266.
What do you think?
</blockquote></details>

Makes sense, thanks
___
*[`book.md` line 2577 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyURfv2JUYAfrykt30:-Nx9NKRP62725UlgWmzk:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2577)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

replace the first "they" with "the".
</blockquote></details>

Done.
___
*[`book.md` line 2578 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyUXv07lYYP6w2DPd7:-Nx9NLMB1Ry_vqYTSsNK:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2578)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

s/kind this/this kind of/
</blockquote></details>

Done.
___
*[`book.md` line 2581 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyUdTg1ejw415XzRDs:-Nx9NMjQAf4wrZf3TtPl:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2581)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

maybe s/formatting/formatting tools/?
</blockquote></details>

Done.
___
*[`book.md` line 2588 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyUoMV0ZU84SEKmktA:-Nx9NNry4Gs2NRFmdaO2:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2588)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

s/to user/to the user/?
</blockquote></details>

Done.
___
*[`book.md` line 2592 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyUyGL8V2RTBOAZXxW:-Nx9JOI-CfTGoKKuInG0:buketii) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2592)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

I'm wondering if "characters" instead of "chars" would be more correct here?
</blockquote></details>

Indeed
___
*[`book.md` line 2597 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyVH957qRXGoMgr9K4:-Nx9I87H182j5TVA--OK:btpt3fo) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2597)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

maybe s/it appears in the file it is after the comment/it appears in the file in, sees it as after the comment/?
</blockquote></details>

Yes.. Tried to clarify by making inside and after italics too. wdyt?
___
*[`book.md` line 2599 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyWBbt7-8dZKVRb7RY:-Nx9I-7lBDj4xlgvgV9I:btlr91g) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2599)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

Maybe it would be useful to also mention that the on the clang side, the decision was to not integrate the check in clang, but rather in clang-tidy, see https://bugs.chromium.org/p/llvm/issues/detail?id=11.
</blockquote></details>

Indeed. Thanks for the reference.
___
*[`book.md` line 2604 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyWgTQ3m7VowhmwUXm:-Nx9NQck5dfXWrl8D6bO:b-896fix) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2604)):*
<details><summary><i>Previously, kbeyls (Kristof Beyls) wrote…</i></summary><blockquote>

Maybe s/As an example/As an example,/?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-06 08:10 UTC, kbeyls approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wanders)

___
*[`book.md` line 2597 at r1](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/239#-NwyVH957qRXGoMgr9K4:-NxBwhchBdnSPJU_3iVG:bpn4dd3) ([raw file](https://github.com/llsoftsec/llsoftsecbook/blob/7b87759abd3b943fd57fca9abd0cb2144434ba7c/book.md#L2597)):*
<details><summary><i>Previously, wanders (Anders Waldenborg) wrote…</i></summary><blockquote>

Yes.. Tried to clarify by making inside and after italics too. wdyt?
</blockquote></details>

Looks good, thank you


<!-- Sent from Reviewable.io -->

2024-05-06 08:10 UTC, merged